# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EDM_multi <- function(Z, min_size = 24L, beta = 0, degree = 0L) {
    .Call('edm_EDM_multi', PACKAGE = 'BreakoutDetection', Z, min_size, beta, degree)
}

EDM_percent <- function(Z, min_size = 24L, percent = 0, degree = 0L) {
    .Call('edm_EDM_percent', PACKAGE = 'BreakoutDetection', Z, min_size, percent, degree)
}

EDM_tail <- function(Z, min_size = 24L, alpha = 2, quant = 0.5) {
    .Call('edm_EDM_tail', PACKAGE = 'BreakoutDetection', Z, min_size, alpha, quant)
}

EDMX <- function(Z, min_size = 24L, alpha = 2) {
    .Call('edm_EDMX', PACKAGE = 'BreakoutDetection', Z, min_size, alpha)
}

