# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EDM_percent <- function(Z, min_size = 24L, percent = 0, degree = 0L) {
    .Call('BreakoutDetection_EDM_percent', PACKAGE = 'BreakoutDetection', Z, min_size, percent, degree)
}

EDM_multi <- function(Z, min_size = 24L, beta = 0, degree = 0L) {
    .Call('BreakoutDetection_EDM_multi', PACKAGE = 'BreakoutDetection', Z, min_size, beta, degree)
}

EDM_tail <- function(Z, min_size, alpha, quant) {
    .Call('BreakoutDetection_EDM_tail', PACKAGE = 'BreakoutDetection', Z, min_size, alpha, quant)
}

EDMX <- function(Z, min_size, alpha) {
    .Call('BreakoutDetection_EDMX', PACKAGE = 'BreakoutDetection', Z, min_size, alpha)
}

